name: My first github action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - run: echo "step no 2"

  print-my-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "my name is Serius Black"
      - run: echo "I belong to slytherin"
