name: My Github Action
on:
  - push
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14.2
      - name: install node-modules
        run: yarn
      - name: Build The project
        run: yarn build
      - name: Setup Finish
        run: echo "hurray"
